apiVersion: v1
kind: Service
metadata:
  name: deployment-two-loadbalancer
spec:
  selector:
    app: nginx
    group: shared
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer