apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-two
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      group: shared
  template:
    metadata:
      labels:
        app: nginx
        group: shared
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: nginx-pvc
      - name: nginx-config
        configMap:
          name: nginx-config