apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      upstream backend {
        server deployment-one:80;
        server deployment-two:80;
      }
      server {
        listen 80;
        root /usr/share/nginx/html;
        index deployment_one_index.html deployment_two_index.html;
        location / {
          proxy_pass http://backend;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx
